YAZLAB2/Models/DietPlan.cs
using System.ComponentModel.DataAnnotations;

namespace YAZLAB2.Models
{
    public class DietPlan
    {
        [Key]
        public int id { get; set; }
        public int danisan_id { get; set; }
        public string danisan_adsoyad { get; set; }
        public string hedefler { get; set; }
    }
}

YAZLAB2/Controllers/AntrenorUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using YAZLAB2;
using YAZLAB2.Models;

namespace YAZLAB2.Controllers
{
    public class AntrenorUserController : Controller
    {
        private readonly YazlabDbContext _context;

        public AntrenorUserController(YazlabDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> RegisterUser(Kullanici kullanici)
        {
            kullanici.rol = "antrenor";

            if (ModelState.IsValid)
            {
                _context.kullanicilar.Add(kullanici);
                await _context.SaveChangesAsync();
                Antrenor a = new Antrenor();
                a.id = kullanici.id;
                a.adsoyad = kullanici.adsoyad;
                _context.antrenorler.Add(a);
                await _context.SaveChangesAsync();
                return View("Details",a);
            }
            else
                return View("Login");
        }

        public async Task<IActionResult> LoginUser(Kullanici k)
        {
            if (_context.kullanicilar.FindAsync(k.id).Result.rol.Equals("antrenor") &&
                _context.kullanicilar.FindAsync(k.id).Result.sifre.Equals(k.sifre))
            {
                SharedClass.id = k.id;
                SharedClass.rol = k.rol;
                SharedClass.loggedin = true;
                Antrenor a = new Antrenor();
                   a=  _context.antrenorler.Find(k.id);

                return View("Details", model: a);
            }
            else if (_context.kullanicilar.FindAsync(k.id).Result.rol.Equals("admin") &&
                _context.kullanicilar.FindAsync(k.id).Result.sifre.Equals(k.sifre))
            {
                SharedClass.id = k.id;
                SharedClass.rol = k.rol;
                SharedClass.loggedin = true;
                return View();
            }
            else
                return BadRequest();
        }
        // GET: AntrenorUser
        public async Task<IActionResult> Index()
        {
              return _context.antrenorler != null ? 
                          View(await _context.antrenorler.ToListAsync()) :
                          Problem("Entity set 'YazlabDbContext.antrenorler'  is null.");
        }

        // GET: AntrenorUser/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.antrenorler == null)
            {
                return NotFound();
            }

            var antrenor = await _context.antrenorler
                .FirstOrDefaultAsync(m => m.id == id);
            if (antrenor == null)
            {
                return NotFound();
            }

            return View(antrenor);
        }

        // GET: AntrenorUser/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AntrenorUser/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,adsoyad,uzmanliklar,deneyim,iletisim")] Antrenor antrenor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(antrenor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(antrenor);
        }
        public async Task<IActionResult> GetClients()
        {
            int id = SharedClass.id;
            List<int> e = _context.eslesmeler.Where(es=> es.antrenor_id == id)
                .Select(es=> es.danisan_id)
                .ToList();
            List<Danısan> eslesmis = new List<Danısan>();
            foreach(int i in e)
            {
                eslesmis.AddRange(_context.danisan.Where(e => e.id == i).ToList());
            }
            return View("Danisanlarim", eslesmis);
        }
        // GET: AntrenorUser/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.antrenorler == null)
            {
                return NotFound();
            }

            var antrenor = await _context.antrenorler.FindAsync(id);
            if (antrenor == null)
            {
                return NotFound();
            }
            return View(antrenor);
        }
        public IActionResult Login()
        {
            return View();
        }

        // POST: AntrenorUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,adsoyad,uzmanliklar,deneyim,iletisim")] Antrenor antrenor)
        {
            if (id != antrenor.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(antrenor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AntrenorExists(antrenor.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(antrenor);
        }

        // GET: AntrenorUser/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.antrenorler == null)
            {
                return NotFound();
            }

            var antrenor = await _context.antrenorler
                .FirstOrDefaultAsync(m => m.id == id);
            if (antrenor == null)
            {
                return NotFound();
            }

            return View(antrenor);
        }
        public async Task<IActionResult> AntPlanUser(int? id)
        {
            id = SharedClass.id;
            List<WorkoutPlan> plans = _context.antrenmanplan
                .Where(e => e.id == id)
                .ToList();




            return View(plans);
        }
        public async Task<IActionResult> DietPlanUser(int? id)
        {
            id = SharedClass.id;
            List<int> e = _context.eslesmeler.Where(es => es.antrenor_id == id)
                .Select(es => es.danisan_id)
                .ToList();
            List<DietPlan> eslesmis = new List<DietPlan>();
            foreach (int i in e)
            {
                eslesmis.AddRange(_context.dietplan.Where(e => e.danisan_id == i).ToList());
            }
            


            return View("DietPlanUser1",eslesmis);
        }
        // POST: AntrenorUser/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.antrenorler == null)
            {
                return Problem("Entity set 'YazlabDbContext.antrenorler'  is null.");
            }
            var antrenor = await _context.antrenorler.FindAsync(id);
            if (antrenor != null)
            {
                _context.antrenorler.Remove(antrenor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public IActionResult CreateDietPlan ()
        {
            return View();
        }

        // POST: DietPlan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateDietPlan([Bind("id,danisan_id,danisan_adsoyad,hedefler")] DietPlan dietPlan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dietPlan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(DietPlanUser));
            }
            return View(dietPlan);
        }

        // GET: DietPlan/Edit/5
        public async Task<IActionResult> EditDietPlan(int? id)
        {
            if (id == null || _context.dietplan == null)
            {
                return NotFound();
            }

            var dietPlan = await _context.dietplan.FindAsync(id);
            if (dietPlan == null)
            {
                return NotFound();
            }
            return View(dietPlan);
        }

        // POST: DietPlan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Editdp(int id, [Bind("id,danisan_id,danisan_adsoyad,hedefler")] DietPlan dietPlan)
        {
            if (id != dietPlan.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dietPlan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DietPlanExists(dietPlan.id))
                    {
                        return NotFound();
                    }

YAZLAB2/Controllers/DietPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YAZLAB2;
using YAZLAB2.Models;

namespace YAZLAB2.Controllers
{
    public class DietPlanController : Controller
    {
        private readonly YazlabDbContext _context;

        public DietPlanController(YazlabDbContext context)
        {
            _context = context;
        }

        // GET: DietPlan
        public async Task<IActionResult> Index()
        {
              return _context.dietplan != null ? 
                          View(await _context.dietplan.ToListAsync()) :
                          Problem("Entity set 'YazlabDbContext.dietplan'  is null.");
        }

        // GET: DietPlan/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.dietplan == null)
            {
                return NotFound();
            }

            var dietPlan = await _context.dietplan
                .FirstOrDefaultAsync(m => m.id == id);
            if (dietPlan == null)
            {
                return NotFound();
            }

            return View(dietPlan);
        }

        // GET: DietPlan/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DietPlan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,danisan_id,danisan_adsoyad,hedefler")] DietPlan dietPlan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dietPlan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dietPlan);
        }

        // GET: DietPlan/Edit/5
        public async Task<IActionResult> Edit(int? plan_id)
        {
            if (plan_id == null || _context.dietplan == null)
            {
                return NotFound();
            }

            var dietPlan = await _context.dietplan.FindAsync(plan_id);
            if (dietPlan == null)
            {
                return NotFound();
            }
            return View(dietPlan);
        }

        // POST: DietPlan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int plan_id, [Bind("id,danisan_id,danisan_adsoyad,hedefler")] DietPlan dietPlan)
        {
            if (plan_id != dietPlan.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dietPlan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DietPlanExists(dietPlan.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dietPlan);
        }

        // GET: DietPlan/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.dietplan == null)
            {
                return NotFound();
            }

            var dietPlan = await _context.dietplan
                .FirstOrDefaultAsync(m => m.id == id);
            if (dietPlan == null)
            {
                return NotFound();
            }

            return View(dietPlan);
        }

        // POST: DietPlan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.dietplan == null)
            {
                return Problem("Entity set 'YazlabDbContext.dietplan'  is null.");
            }
            var dietPlan = await _context.dietplan.FindAsync(id);
            if (dietPlan != null)
            {
                _context.dietplan.Remove(dietPlan);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DietPlanExists(int id)
        {
          return (_context.dietplan?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

YAZLAB2/Views/DietPlan/Create.cshtml
@model YAZLAB2.Models.DietPlan

@{
    ViewData["Title"] = "Create";
    Layout = "_AntrenorLayout";
}

<h1>Create</h1>

<h4>DietPlan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="id" class="control-label"></label>
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger"></span>
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="danisan_id" class="control-label"></label>
                <input asp-for="danisan_id" class="form-control" />
                <span asp-validation-for="danisan_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="danisan_adsoyad" class="control-label"></label>
                <input asp-for="danisan_adsoyad" class="form-control" />
                <span asp-validation-for="danisan_adsoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="hedefler" class="control-label"></label>
                <input asp-for="hedefler" class="form-control" />
                <span asp-validation-for="hedefler" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

YAZLAB2/Views/DietPlan/Delete.cshtml
@model YAZLAB2.Models.DietPlan

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DietPlan</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.danisan_id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.danisan_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.danisan_adsoyad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.danisan_adsoyad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hedefler)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hedefler)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

YAZLAB2/Views/DietPlan/Details.cshtml
@model YAZLAB2.Models.DietPlan

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>DietPlan</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.danisan_id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.danisan_id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.danisan_adsoyad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.danisan_adsoyad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hedefler)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hedefler)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

YAZLAB2/Views/DietPlan/Edit.cshtml
@model YAZLAB2.Models.DietPlan

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>DietPlan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="danisan_id" class="control-label"></label>
                <input asp-for="danisan_id" class="form-control" />
                <span asp-validation-for="danisan_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="danisan_adsoyad" class="control-label"></label>
                <input asp-for="danisan_adsoyad" class="form-control" />
                <span asp-validation-for="danisan_adsoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="hedefler" class="control-label"></label>
                <input asp-for="hedefler" class="form-control" />
                <span asp-validation-for="hedefler" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

YAZLAB2/Views/DietPlan/Index.cshtml
@model IEnumerable<YAZLAB2.Models.DietPlan>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.danisan_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.danisan_adsoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hedefler)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayNameFor(model => model.id)
                </td>
                <td>
                    @Html.DisplayNameFor(model => model.danisan_id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.danisan_adsoyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hedefler)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

YAZLAB2/Views/DietPlan/_AntrenorLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YAZLAB2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YAZLAB2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Heavy Duty Ant Konsolu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AntrenorUser" asp-action="GetClients">Danısanlarım</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AntrenorUser" asp-action="Details">Bilgilerim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DietPlan" asp-action="Index">Diyet Planları</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Antrenmanplan" asp-action="Index">
                                Antrenman
                                Planları
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - YAZLAB2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>