YAZLAB2/Controllers/AntrenorlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YAZLAB2;
using YAZLAB2.Models;

namespace YAZLAB2.Controllers
{
    public class AntrenorlerController : Controller
    {
        private readonly YazlabDbContext _context;

        public AntrenorlerController(YazlabDbContext context)
        {
            _context = context;
        }

        // GET: Antrenorler
        public async Task<IActionResult> Index()
        {
              return _context.antrenorler != null ? 
                          View(await _context.antrenorler.ToListAsync()) :
                          Problem("Entity set 'YazlabDbContext.antrenorler'  is null.");
        }

        // GET: Antrenorler/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.antrenorler == null)
            {
                return NotFound();
            }

            var antrenor = await _context.antrenorler
                .FirstOrDefaultAsync(m => m.id == id);
            if (antrenor == null)
            {
                return NotFound();
            }

            return View(antrenor);
        }

        // GET: Antrenorler/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Antrenorler/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,adsoyad,uzmanliklar,deneyim,iletisim")] Antrenor antrenor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(antrenor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(antrenor);
        }

        // GET: Antrenorler/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.antrenorler == null)
            {
                return NotFound();
            }

            var antrenor = await _context.antrenorler.FindAsync(id);
            if (antrenor == null)
            {
                return NotFound();
            }
            return View(antrenor);
        }

        // POST: Antrenorler/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,adsoyad,uzmanliklar,deneyim,iletisim")] Antrenor antrenor)
        {
            if (id != antrenor.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(antrenor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AntrenorExists(antrenor.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(antrenor);
        }

        // GET: Antrenorler/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.antrenorler == null)
            {
                return NotFound();
            }

            var antrenor = await _context.antrenorler
                .FirstOrDefaultAsync(m => m.id == id);
            if (antrenor == null)
            {
                return NotFound();
            }

            return View(antrenor);
        }

        // POST: Antrenorler/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.antrenorler == null)
            {
                return Problem("Entity set 'YazlabDbContext.antrenorler'  is null.");
            }
            var antrenor = await _context.antrenorler.FindAsync(id);
            if (antrenor != null)
            {
                _context.antrenorler.Remove(antrenor);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AntrenorExists(int id)
        {
          return (_context.antrenorler?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

YAZLAB2/Controllers/DietPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YAZLAB2;
using YAZLAB2.Models;

namespace YAZLAB2.Controllers
{
    public class DietPlanController : Controller
    {
        private readonly YazlabDbContext _context;

        public DietPlanController(YazlabDbContext context)
        {
            _context = context;
        }

        // GET: DietPlan
        public async Task<IActionResult> Index()
        {
              return _context.dietplan != null ? 
                          View(await _context.dietplan.ToListAsync()) :
                          Problem("Entity set 'YazlabDbContext.dietplan'  is null.");
        }

        // GET: DietPlan/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.dietplan == null)
            {
                return NotFound();
            }

            var dietPlan = await _context.dietplan
                .FirstOrDefaultAsync(m => m.id == id);
            if (dietPlan == null)
            {
                return NotFound();
            }

            return View(dietPlan);
        }

        // GET: DietPlan/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DietPlan/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,danisan_id,danisan_adsoyad,hedefler")] DietPlan dietPlan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dietPlan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dietPlan);
        }

        // GET: DietPlan/Edit/5
        public async Task<IActionResult> Edit(int? plan_id)
        {
            if (plan_id == null || _context.dietplan == null)
            {
                return NotFound();
            }

            var dietPlan = await _context.dietplan.FindAsync(plan_id);
            if (dietPlan == null)
            {
                return NotFound();
            }
            return View(dietPlan);
        }

        // POST: DietPlan/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int plan_id, [Bind("id,danisan_id,danisan_adsoyad,hedefler")] DietPlan dietPlan)
        {
            if (plan_id != dietPlan.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dietPlan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DietPlanExists(dietPlan.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dietPlan);
        }

        // GET: DietPlan/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.dietplan == null)
            {
                return NotFound();
            }

            var dietPlan = await _context.dietplan
                .FirstOrDefaultAsync(m => m.id == id);
            if (dietPlan == null)
            {
                return NotFound();
            }

            return View(dietPlan);
        }

        // POST: DietPlan/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.dietplan == null)
            {
                return Problem("Entity set 'YazlabDbContext.dietplan'  is null.");
            }
            var dietPlan = await _context.dietplan.FindAsync(id);
            if (dietPlan != null)
            {
                _context.dietplan.Remove(dietPlan);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DietPlanExists(int id)
        {
          return (_context.dietplan?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

YAZLAB2/Controllers/danisanlarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using YAZLAB2;
using YAZLAB2.Models;

namespace YAZLAB2.Controllers
{
    public class danisanlarController : Controller
    {
        private readonly YazlabDbContext _context;

        public danisanlarController(YazlabDbContext context)
        {
            _context = context;
        }

        // GET: danisanlar
        public async Task<IActionResult> Index()
        {
              return _context.danisan != null ? 
                          View(await _context.danisan.ToListAsync()) :
                          Problem("Entity set 'YazlabDbContext.danisan'  is null.");
        }

        // GET: danisanlar/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.danisan == null)
            {
                return NotFound();
            }

            var danısan = await _context.danisan
                .FirstOrDefaultAsync(m => m.id == id);
            if (danısan == null)
            {
                return NotFound();
            }

            return View(danısan);
        }

        // GET: danisanlar/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: danisanlar/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,adsoyad,hedefler,boy,kilo,bmi,yagorani")] Danısan danısan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(danısan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(danısan);
        }

        // GET: danisanlar/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.danisan == null)
            {
                return NotFound();
            }

            var danısan = await _context.danisan.FindAsync(id);
            if (danısan == null)
            {
                return NotFound();
            }
            return View(danısan);
        }

        // POST: danisanlar/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,adsoyad,hedefler,boy,kilo,bmi,yagorani")] Danısan danısan)
        {
            if (id != danısan.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danısan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanısanExists(danısan.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(danısan);
        }

        // GET: danisanlar/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.danisan == null)
            {
                return NotFound();
            }

            var danısan = await _context.danisan
                .FirstOrDefaultAsync(m => m.id == id);
            if (danısan == null)
            {
                return NotFound();
            }

            return View(danısan);
        }

        // POST: danisanlar/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.danisan == null)
            {
                return Problem("Entity set 'YazlabDbContext.danisan'  is null.");
            }
            var danısan = await _context.danisan.FindAsync(id);
            if (danısan != null)
            {
                _context.danisan.Remove(danısan);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DanısanExists(int id)
        {
          return (_context.danisan?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

YAZLAB2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YAZLAB2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YAZLAB2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gym Admin Konsolu</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Antrenorler" asp-action="Index">Antrenor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="danisanlar" asp-action="Index">Danışan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DietPlan" asp-action="Index">Diyet Planları</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Antrenmanplan" asp-action="Index">Antrenman
                                Planları
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="kullanicilar" asp-action="Index">
                                Kullanıcılar
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - YAZLAB2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

YAZLAB2/Views/Shared/_NoLoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YAZLAB2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YAZLAB2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HEAVY DUTY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanisanUser" asp-action="Login">Danışan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AntrenorUser" asp-action="Login">Antrenör</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="antrenor" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - YAZLAB2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>