YAZLAB2/Models/Eslesmeler.cs
using Microsoft.EntityFrameworkCore;

namespace YAZLAB2.Models
{
    [Keyless]
    public class Eslesmeler
    {
        public int danisan_id { get; set; }
        public string danisan_adsoyad { get; set; }
        public int antrenor_id { get; set; } 
        public string antrenor_adsoyad { get; set; }
        public string alan { get; set; }
        public Eslesmeler() { }
    }
}

YAZLAB2/Controllers/DanisanUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ActionConstraints;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Npgsql;
using Microsoft.EntityFrameworkCore;

using YAZLAB2.Models;
using Npgsql.Internal;
using System.Data;
using System.Collections.Immutable;

namespace YAZLAB2.Controllers
{
    public class DanisanUserController : Controller
    {
        
        private readonly YazlabDbContext _context;

        public DanisanUserController(YazlabDbContext context)
        {
           
            _context = context;
        }
        public IActionResult Login()
        {
            return View();
        }

        // GET: DanisanUser
        public async Task<IActionResult> Index(int? id)
        {
            id = SharedClass.id;
            if (id == null || _context.danisan == null)
            {
                return NotFound();
            }
            

            var danısan = await _context.danisan
                .FirstOrDefaultAsync(m => m.id == id);
            if (danısan == null)
            {
                return NotFound();
            }

            return View("DanisanIndex",danısan);
        }
        public async Task<IActionResult> RegisterUser(Kullanici kullanici)
        {

            if (ModelState.IsValid)
            {
                _context.kullanicilar.Add(kullanici);
                await _context.SaveChangesAsync();
                    Danısan d = new Danısan();
                    d.id = kullanici.id;
                    d.adsoyad = kullanici.adsoyad;
                    _context.danisan.Add(d);
                    await _context.SaveChangesAsync();
                    return View("Login");
                
            }
            else 
                return View("Login");
        }
        public async Task<IActionResult> LoginUser(Kullanici k)
        {
            if (_context.kullanicilar.FindAsync(k.id).Result.rol.Equals("danisan")&&
                _context.kullanicilar.FindAsync(k.id).Result.sifre.Equals(k.sifre))
            {
                SharedClass.id = k.id;
                SharedClass.rol = k.rol;
                SharedClass.loggedin = true;
                Danısan d = _context.danisan.Find(k.id);

                return View("DanisanIndex", model: d);
            }
            else if (_context.kullanicilar.FindAsync(k.id).Result.rol.Equals("admin")&&
                _context.kullanicilar.FindAsync(k.id).Result.sifre.Equals(k.sifre))
            {
                SharedClass.id = k.id;
                SharedClass.rol = k.rol;
                SharedClass.loggedin = true;
                return View();
            }
            else
                return BadRequest();
        }




        // GET: DanisanUser/Edit/5

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.danisan == null)
            {
                return NotFound();
            }

            var danısan = await _context.danisan.FindAsync(id);
            if (danısan == null)
            {
                return NotFound();
            }
            return View();
        }

        // POST: DanisanUser/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,adsoyad,hedefler,boy,kilo,bmi,yagorani")] Danısan danısan)
        {
            if (id != danısan.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(danısan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DanısanExists(danısan.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return View("DanisanIndex");
            }
            return View("DanisanIndex");
        }
        public IActionResult match(int? id)
        {
            string connectionString = "Host=localhost; Database=postgres; Username=postgres; Password=Talha2003";
            id = SharedClass.id;
            List<Antrenor> a = new List<Antrenor>();
            using (NpgsqlConnection connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();

                string Query = "SELECT d.id, d.adsoyad, a.id, a.adsoyad, a.uzmanliklar\r\nFROM danisan d\r\nINNER JOIN antrenorler a ON d.hedefler = a.uzmanliklar\r\nWHERE NOT EXISTS (\r\n    SELECT 1\r\n    FROM eslesmeler e\r\n    WHERE e.danisan_id = d.id AND e.antrenor_id = a.id\r\n) AND d.id =" + id;

                using (NpgsqlCommand command = new NpgsqlCommand(Query, connection))
                {
                 using(NpgsqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Antrenor an = new Antrenor();
                            an.id = reader.GetInt32(2);
                            an.adsoyad=reader.GetString(3);
                            an.uzmanliklar = reader.GetString(4);
                            a.Add(an);
                        }
                    }
                }
                connection.Close();
            }
            return View("Eslesmeler", a);
        }
        public IActionResult egitmenlerim(int? id)
        {
            id = SharedClass.id;
            List<Eslesmeler> a = _context.eslesmeler.Where(e=>e.danisan_id==id).ToList();
            return View(a);

        }
        public async Task<IActionResult> eslestir(int id)
        {
            var an = await _context.antrenorler
                .FirstOrDefaultAsync(m => m.id == id);


            string connectionString = "Host=localhost; Database=postgres; Username=postgres; Password=Talha2003";
            using (NpgsqlConnection connection = new NpgsqlConnection(connectionString))
            {
                connection.Open();
                Danısan d = _context.danisan.Find(SharedClass.id);
                using (NpgsqlCommand command = new NpgsqlCommand("INSERT INTO eslesmeler VALUES (@SharedId, @DanisanAdSoyad, @AntrenorId, @AntrenorAdSoyad, @Uzmanlik);", connection))
                {
                    command.Parameters.AddWithValue("@SharedId", SharedClass.id);
                    command.Parameters.AddWithValue("@DanisanAdSoyad", d.adsoyad);
                    command.Parameters.AddWithValue("@AntrenorId", id);
                    command.Parameters.AddWithValue("@AntrenorAdSoyad", an.adsoyad );
                    command.Parameters.AddWithValue("@Uzmanlik", an.uzmanliklar);
 

                    // Execute the command
                    command.ExecuteNonQuery();
                }
                connection.Close();
            }
            return View("DanisanIndex");
        }
        public async Task<IActionResult> AntPlanUser(int? id)
        {
            id = SharedClass.id;
            List<WorkoutPlan> plans = _context.antrenmanplan
                .Where(e => e.id == id)
                .ToList();




            return View(plans);
        }
        public async Task<IActionResult> DietPlanUser(int? id)
        {
            id = SharedClass.id;
            List<DietPlan> plans = _context.dietplan
                .Where(e => e.danisan_id == id)
                .ToList();




            return View(plans);
        }
        private bool DanısanExists(int id)
        {
          return (_context.danisan?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

YAZLAB2/Views/DanisanUser/AntPlanUser.cshtml
@model IEnumerable<YAZLAB2.Models.WorkoutPlan>

@{
    ViewData["Title"] = "AntPlanUser";
    Layout = "_DanisanLayout";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.danisan_adsoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hedefler)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>
                    @Html.DisplayNameFor(model => model.id)
             </td>
            <td>
                @Html.DisplayFor(modelItem => item.danisan_adsoyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hedefler)
            </td>
        </tr>
}
    </tbody>
</table>

YAZLAB2/Views/DanisanUser/DanisanIndex.cshtml
@model YAZLAB2.Models.Danısan

@{
    ViewData["Title"] = "DanisanIndex";
    Layout = "_DanisanLayout.cshtml";
}

<h1>Bilgilerim</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.adsoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hedefler)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.boy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.kilo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bmi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.yagorani)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        <tr>
            <td>
                @Html.DisplayFor(item => item.adsoyad)
            </td>
            <td>
                @Html.DisplayFor(item => item.hedefler)
            </td>
            <td>
                @Html.DisplayFor(item => item.boy)
            </td>
            <td>
                @Html.DisplayFor(item => item.kilo)
            </td>
            <td>
                @Html.DisplayFor(item => item.bmi)
            </td>
            <td>
                @Html.DisplayFor(item => item.yagorani)
            </td>
            <td>
                <a asp-controller="DanisanUser" asp-action="Edit" asp-route-id="@Model?.id">Edit</a> | |
            </td>
        </tr>
    </tbody>
</table>

YAZLAB2/Views/DanisanUser/DietPlanUser.cshtml
@model IEnumerable<YAZLAB2.Models.DietPlan>

@{
    ViewData["Title"] = "Index";
    Layout = "_DanisanLayout";
}

<h1>Index</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.danisan_adsoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hedefler)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.danisan_adsoyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hedefler)
            </td>
            <td>
                
            </td>
        </tr>
}
    </tbody>
</table>

YAZLAB2/Views/DanisanUser/Edit.cshtml
@model YAZLAB2.Models.Danısan

@{
    ViewData["Title"] = "Edit";
    Layout = "_DanisanLayout.cshtml";
}

<h1>Edit</h1>

<h4>Danısan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="adsoyad" class="control-label"></label>
                <input asp-for="adsoyad" class="form-control" />
                <span asp-validation-for="adsoyad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="hedefler" class="control-label"></label>
                <input asp-for="hedefler" class="form-control" />
                <span asp-validation-for="hedefler" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="boy" class="control-label"></label>
                <input asp-for="boy" class="form-control" />
                <span asp-validation-for="boy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="kilo" class="control-label"></label>
                <input asp-for="kilo" class="form-control" />
                <span asp-validation-for="kilo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="bmi" class="control-label"></label>
                <input asp-for="bmi" class="form-control" />
                <span asp-validation-for="bmi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="yagorani" class="control-label"></label>
                <input asp-for="yagorani" class="form-control" />
                <span asp-validation-for="yagorani" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

YAZLAB2/Views/DanisanUser/Eslesmeler.cshtml
@model IEnumerable<YAZLAB2.Models.Antrenor>

@{
    ViewData["Title"] = "Eslesmeler";
    Layout = "_DanisanLayout";
}

<h1>Eslesmeler</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.adsoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.uzmanliklar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.deneyim)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.iletisim)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.adsoyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.uzmanliklar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.deneyim)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.iletisim)
            </td>
            <td>
                <a asp-action="eslestir" asp-route-id="@item.id">eslestir</a> |
                
            </td>
        </tr>
}
    </tbody>
</table>

YAZLAB2/Views/DanisanUser/Login.cshtml
@model YAZLAB2.Models.Kullanici
@{
    ViewData["Title"] = "Login";
    Layout = "_NoLoginLayout";
}

<div class="text-center">
    <h1 class="display-4">Yazlab GYM</h1>
    <p><a href="https://www.youtube.com/watch?v=852rGXEa5wQ">BECOME THE OVERMAN</a>.</p>

    <!-- Login Form -->
    <div class="container mt-4">
        <h2>Login</h2>
        <form asp-controller="DanisanUser" asp-action="LoginUser" method="get">
            <div class="form-group">
                <label for="loginID">ID:</label>
                <input type="texT" class="form-control" id="ID" name="id" required>
            </div>
            <div class="form-group">

                <label for="loginPassword">Password:</label>
                <input type="password" class="form-control" id="loginPassword" name="sifre" required>
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
        </form>
    </div>

    <!-- Register Form -->
    <div class="container mt-4">
        <h2>Register</h2>
        <form asp-controller="DanisanUser" asp-action="RegisterUser" method="post">
            <div class="form-group">
                <label for="registerID">ID:</label>
                <input type="text" class="form-control" id="registerID" name="ID" required>
            </div>
            <div class="form-group">
                <label for="registerEmail">eposta:</label>
                <input type="email" class="form-control" id="registerEmail" name="eposta" required>
            </div>
            <div class="form-group">
                <label for="registerAdsoyad">Adsoyad:</label>
                <input type="text" class="form-control" id="registerAdsoyad" name="adsoyad" required>
            </div>
            <div class="form-group">
                <label for="registerPassword">Sifre:</label>
                <input type="password" class="form-control" id="registerPassword" name="sifre" required>
            </div>
            <div class="form-group">
                <label for="registerPassword">rol:</label>
                <input type="text" class="form-control" id="registerRol" name="rol" required>
            </div>
            <button type="submit" class="btn btn-success">Register</button>
        </form>
    </div>
</div>

YAZLAB2/Views/DanisanUser/_DanisanLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - YAZLAB2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/YAZLAB2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Heavy duty danısan</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanisanUser" asp-action="Index">Ana sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanisanUser" asp-action="egitmenlerim">Eğitmenlerim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanisanUser" asp-action="Index">Bilgilerim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanisanUser" asp-action="DietPlanUser">Diyet Planları</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanisanUser" asp-action="AntPlanUser">
                                Antrenman
                                Planları
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DanisanUser" asp-action="match">Eslesmeler</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - YAZLAB2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

YAZLAB2/Views/DanisanUser/egitmenlerim.cshtml
@model IEnumerable<YAZLAB2.Models.Eslesmeler>

@{
    ViewData["Title"] = "Egitmenlerim";
    Layout = "_DanisanLayout";
}

<h1>Eslesmeler</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.antrenor_id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.antrenor_adsoyad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.alan)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.antrenor_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.antrenor_adsoyad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.alan)
                </td>
            </tr>
        }
    </tbody>
</table>